### ISSUE TITLE
question for 5887bb9.

### ISSUE THREAD

**Issue by jinsankim** [magicdlf/huobipro#2]
Hi magicdlf,

I'm interested in this change#5887bb9. I also encountered ESOCKETTIMEDOUT issue for huobi rest API. I have two questions. If you could answer these questions, I'll really appreciate for it.

Has this change worked for you? Is ESOCKETTIMEOUT issue totally disappeared or significantly reduced?

Why do you think 'keepAlive' affects ESOCKETTIMEOUT issue?

I actually tried to apply this change to my code, but it doesn't work for my case. :(

Thanks in advance,

你好magicdlf，

我对这种变化感兴趣。 我也遇到了针对huobi rest API的ESOCKETTIMEDOUT问题。 我有两个问题。 如果你能回答这些问题，我将非常感激。

1.这个改变对你有用吗？ ESOCKETTIMEOUT问题是完全消失还是显着减少？

2.为什么你认为'keepAlive'会影响ESOCKETTIMEOUT问题？

实际上我试图将此更改应用于我的代码，但它不适用于我的情况。:(

提前致谢，

**Comment by magicdlf** [comment]
Well it matters when you deal with the load balancer. It looks to me that the server will disconnect me randomly when I using the keepAlive option at that time, so I removed it. Actually when you use a longer keepAliveMsecs option, keepAlive option works well...

var agentOptions = {
    //maxSockets如果设置成1，同一个host:port只保留一个连接，会产生堆积
    //理论上设置成256也没问题，只不过会保持更多的连接而已
    maxSockets: 20,
    keepAlive: true,
    keepAliveMsecs: 300000,
}

**Comment by magicdlf** [comment]
Vy the way, ESOCKETTIMEOUT is usually caused by Huobi side, sometimes the server has received the request but just not respond. moving your server to the same AZ is very important.

**Comment by jinsankim** [comment]
I really appreciate for your reply!!

I'll try the option which you let me know.

> ESOCKETTIMEOUT is usually caused by Huobi side, sometimes the server has received the request but just not respond

That's exactly what I'm suffered from.

I read the API-FAQ (https://github.com/huobiapi/API-FAQ/wiki) through google translator. I found the suggestion to use Japan Cloud Server like Amazon.

> 经常断线或者丢数据
请使用日本云服务器

> moving your server to the same AZ is very important.

Did you mean that I should move my server to Japan Amazon in order to fix the socket timeout issue like API-FAQ document?

Thanks,

**Comment by magicdlf** [comment]
Issue Closed
